#!/bin/bash

echo removing old files
rm -rf static

echo bundling files
parcel build views/index.html --dist-dir static

echo pushing to repository
git add .
git commit -m "deploying"

echo patching version
npm version patch && exit 1
git push && exit 1

echo deploying to production
pm2 deploy deploy.config.cjs production