export const NEW_EVENT = "NEW_EVENT";
export const UPDATE_STREAM = "UPDATE_STREAM";
export const FETCH_STREAMS = "FETCH_STREAMS";
export const UPDATE_PROCESS = "UPDATE_PROCESS";

export const EVENTS_COUNT_RECEIVED = "EVENTS_COUNT_RECEIVED";
export const STREAMS_RECEIVED = "STREAMS_RECEIVED";
export const PROCESS_RECEIVED = "PROCESS_RECEIVED";
